### ISSUE TITLE
PHP backend?

### ISSUE THREAD

**Issue by DQ318** [MahmoudElbokl/News-Me#1]
@MahmoudElbokl 

Wow, really cool !!!

I really liked the App.
Would it be possible to use PHP as a backend, instead of the API provided by https://newsapi.org ??

I am developing a small blog in PHP and I would like to show my posts on the App.

Again, very good work. :)

**Comment by MahmoudElbokl** [comment]
sorry for the delay,

Yes, we can add the blog posts to the app.

you can contact me directly on my LinkedIn.

Thanks
